# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values which you are expected to set up once and rarely edit after that.
#
# Advanced users: If you find yourself editing this file very often, consider using Jekyll's data files feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'.
#
# If you are developing on your local computer and you change this file, please restart the local server process.


# ================================
# Site information
#
# SEE THE WIKI PAGE BELOW for information on what each of these settings mean:
#
# url
# ================================
url: "http://civic.tools"

title: "Civic Tools"

description: "Providing tools for the people!"

author: "Civic Tools"

logo-headline: "Civic Tools"

sheet-url: ""



# ================================
# Enable/Disable Features
#
# SEE THE WIKI PAGE BELOW FOR ACTIONS YOU MUST TAKE WHEN YOU CHANGE THESE OPTIONS:
#
# url here
# ================================
logo-enabled: true

social-links-enabled: true

sharing-enabled: false

news-enabled: true

submit-enabled: true

past-events-enabled: false



# ================================
# Appearance
#
# SEE THE WIKI PAGE BELOW FOR ACTIONS YOU MUST TAKE WHEN YOU CHANGE THESE OPTIONS:
#
# url here
#
# ================================
theme-color: default
font-combo: default



# ================================
# Google Analytics
#
# # SEE THE WIKI PAGE BELOW for information on how to set up Google Analytics:
#
# url here
#
# ================================
stuff: ""



# ================================
# Article Image Helper - DONT CHANGE THIS
# ================================
article_image: /assets/images/posts



# ================================
# Collections - ADVANCED USERS MAY CHANGE
#
# SEE THE WIKI PAGE BELOW for information on how to change the name of the "news" section or to create additional collections (site sections):
#
# url here
#
# ================================
collections:
  news:
    output: true
    permalink: /:collection/:slug



# ================================
# Build Settings - DONT CHANGE THESE
# ================================
markdown: kramdown
theme: minima
gems:
  #- jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - gulpfile.js
sass:
    sass_dir: _source_assets/sass-jekyll
