# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values which you are expected to set up once and rarely edit after that.
#
# Advanced users: If you find yourself editing this file very often, consider using Jekyll's data files feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'.
#
# If you are developing on your local computer and you change this file, please restart the local server process.


# ================================
# Site information
# ================================
title: Civic Tools

description: Providing tools for the people!

author: Civic Tools

email: toolscivic@gmail.com

url: "http://civic.tools"

baseurl: ""



# ================================
# Appearance
# ================================
theme-color: default
font-combo: default



# ================================
# Build Settings
# ================================
markdown: kramdown
gems:
  # jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - gulpfile.js
sass:
    sass_dir: _sass-jekyll
